### PR TITLE
Remove `.js` from `.umd` suffix

### PR DESCRIPTION
**Pull request by seanpdoyle**
https://github.com/emberjs/emberjs-build/pull/94#discussion_r28895145

### CODE REVIEW

**Comment by seanpdoyle** [comment]
ping: @stefanpenner

**Comment by stefanpenner** [comment]
LGTM @seanpdoyle I owe you :beers:

**Comment by seanpdoyle** [comment]
@stefanpenner this one's green.

**Comment by seanpdoyle** [comment]
@stefanpenner with this merged, https://github.com/emberjs/ember.js/pull/10853 is still failing.

https://travis-ci.org/emberjs/ember.js/jobs/65799159#L150

```js
// run_loop.js

var backburner = new Backburner(['sync', 'actions', 'destroy'], {
// ...
```

`Backburner` is undefined at this point.

Any suggestions?

**Comment by stefanpenner** [comment]
master appears fine, what is the difference?

**Comment by stefanpenner** [comment]
is your cleanup branch rebased?

**Pull request merged**
