### PR TITLE
Pull #135 fix and test together for merge

### PR DESCRIPTION
**Pull request by rondale-sc**
Just a PR that pulls in the work from @rbarbey and @ducarroz together.  For more information about these please see #135 and #137

### CODE REVIEW

**Comment by stefanpenner** [comment]
@krisselden would love your eyeballs on this.

**Comment by rwjblue** [comment]
We need to fix this in Ember.  Who should I hound for review?

**Comment by stefanpenner** [comment]
@krisselden

**Comment by krisselden** [comment]
I'll try to check it out in a moment, but setting `wait=0` isn't the type of code I'd generally merge, either fix the bug in calculating the wait time or remove the code that waits, don't set wait to 0.

**Comment by ducarroz** [comment]
in my understanding, we reach that code because we are already over due with the timer, therefore the waiting time should be 0 as we need to fire right away...

**Comment by stefanpenner** [comment]
@krisselden I believe @ducarroz explanation if correct. I just want to double check with you to make sure we aren't missing something

**Comment by rbarbey** [comment]
> in my understanding, we reach that code because we are already over due with the timer, therefore the waiting time should be 0 as we need to fire right away...
> 
That's exactly right.

**Comment by krisselden** [comment]
@ducarroz if that is the case why did we cancel it? I still feel like this fix is too far downstream of the problem.

**Comment by krisselden** [comment]
The problem is when you do too many fixes without root cause analysis it just makes the library unmaintainable.  From what you are describing, this seems to be the root cause https://github.com/ebryn/backburner.js/blob/master/lib/backburner.js#L503-L506 we are canceling a good timer and rescheduling.

Furthermore, I find it dubious that we deal in 'wait' and 'executeAt', relative should be immediately converted to absolute, and reconverted to wait just before scheduling the next flush.

I won't block merging, but this path is just going to continue down the path of more needless complexity.

**Comment by ducarroz** [comment]
@krisselden backburner is using a single timeout to handle all the tasks scheduled with run.later. The problem is that is possible the timeout does not fire on time because some JS takes too much time to execute. If another task is scheduled before JS had a chance to fire the timeout (after the expected time), the current code believe the timeout is expired and cancel it, then reschedule a new one for what it believe should be the next task to run, causing the initial task to be delayed until the next one fires.

**Comment by stefanpenner** [comment]
I'm still not understanding @krisselden's concern.

**Comment by stefanpenner** [comment]
Ah actually a quick skim of the code pointed to does make me nervous. This isn't how I remember it :p

**Comment by krisselden** [comment]
@ducarroz that is the problem, the timer shouldn't be canceled and rescheduled, the code on the line I linked to shouldn't cancel it and shouldn't call this method. None of this code should be in this method, the fact this method takes both a wait and executeAt means that it has had too many issues fixed in the same manner.

**Comment by rbarbey** [comment]
@krisselden I totally agree that it would be better to overhaul the approach how timers are handled. I would suggest to merge the fix now and create a separate issue which deals with a fundamental refactor of the code. I'd be more than happy to work on it.

**Pull request closed without merging**
