### PR TITLE
[breaking] Use native `Date.now()`

### PR DESCRIPTION
**Pull request by tricknotes**
Ember doesn't support IE < 9 anymore.

### CODE REVIEW

**Comment by tricknotes** [comment]
This PR will conflict with https://github.com/ebryn/backburner.js/pull/165.
I'll rebase after the one of them landed.

**Comment by stefanpenner** [comment]
Lgtm

**Comment by tricknotes** [comment]
Thanks!
Now I rebased.

**Comment by stefanpenner** [comment]
Will merge when ci completes

**Pull request merged**
